# Generated by Django 3.0.3 on 2020-02-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='meet_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='results_url',
            field=models.URLField(null=True),
        ),
    ]
